feat: Dependency structure of metavariables
reaslab/jixia pull request #5
Opened 2024-09-11 09:48 UTC by meow-sister

2024-09-12 04:03 UTC, tonyxty requested changes
Also please add your id to the copyright notice at the header of the files.

2024-09-12 04:03 UTC, tonyxty commented on Analyzer/Goal.lean
Can you serialize MVarId as `Name`, to keep it consistent with how we handled `FVarId`?

2024-09-13 08:17 UTC, znssong commented on Analyzer/Goal.lean
These are finished.

2024-09-21 11:58 UTC, tonyxty commented on Analyzer/Process/Elaboration.lean
It seems to me that the modifications made here changes code behavior:

`typeUses` and `valueUses` are intended to record the references to free variables in the final solution of the metavariable, i.e., after the entire tactic block has been elaborated.

This might be derived from the more refined dependency graph though, so I need some time to look into it.

2024-10-22 07:03 UTC, tonyxty approved these changes

2024-10-22 07:04 UTC, merged